produto/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('categoria/<str:cat>/', views.category, name='category'),
    path('produto/<str:slug>/', views.produto, name='produto'),
    path('carrinho/', views.cart, name='cart'),
    path('adicionaraocarrinho/', views.add_to_cart, name='addtocart'),
    path('removerdocarrinho/<str:varid>', views.remove_from_cart, name='removefromcart'),
    path('resumodacompra/', views.summary, name='summary'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('produto.urls')),
	path('perfis/', include('perfil.urls')),
	path('pedido/', include('pedido.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/models.py
from pyexpat import model
from django.db import models
from django.utils.text import slugify


class Produto(models.Model):
	nome = models.CharField(max_length=255)
	descricao_curta = models.TextField(max_length=255)
	descricao_longa = models.TextField()
	imagem = models.ImageField(
		upload_to='product_images/%Y/%m/', blank=True, null=True)
	slug = models.SlugField(unique=True, blank=True, null=True)
	destaque = models.BooleanField(default=False)
	preco_minimo = models.FloatField()
	preco_maximo = models.FloatField(
        default=0, null=True, blank=True)
	categoria = models.CharField(
		default='',
		max_length=1,
		choices=(
			('C', 'Casacos'),
			('M', 'Moletons'),
			('B', 'Blusas'),
			('A', 'Calças'),
		)
	)

	def __str__(self):
		return self.nome

	
	def save(self, *args, **kwargs):
		if not self.slug:
			slug = f'{slugify(self.nome)}'
			self.slug = slug

		super().save(*args, **kwargs)


class Variacao(models.Model):
	produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
	nome = models.CharField(max_length=50, null=True, blank=True)
	preco = models.FloatField()
	estoque = models.PositiveIntegerField(default=1)


	def __str__(self):
		return self.nome or self.produto.nome


	class Meta:
		verbose_name = 'Variação'
		verbose_name_plural = 'Variações'

produto/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Produto, Variacao


def home(req):
	destaques = Produto.objects.filter(destaque=True)

	casacos = Produto.objects.filter(categoria='C')
	preco_minimo_casaco = 100000
	for casaco in casacos:
		if casaco.preco_minimo < preco_minimo_casaco:
			preco_minimo_casaco = casaco.preco_minimo

	moletoms = Produto.objects.filter(categoria='M')
	preco_minimo_moletom = 100000
	for moletom in moletoms:
		if moletom.preco_minimo < preco_minimo_moletom:
			preco_minimo_moletom = moletom.preco_minimo

	blusas = Produto.objects.filter(categoria='B')
	preco_minimo_blusa = 100000
	for blusa in blusas:
		if blusa.preco_minimo < preco_minimo_blusa:
			preco_minimo_blusa = blusa.preco_minimo

	calcas = Produto.objects.filter(categoria='A')
	preco_minimo_calca = 100000
	for calca in calcas:
		if calca.preco_minimo < preco_minimo_calca:
			preco_minimo_calca = calca.preco_minimo
	
	context = {
		'destaques': destaques,
		'preco_minimo_casaco': preco_minimo_casaco,
		'preco_minimo_moletom': preco_minimo_moletom,
		'preco_minimo_blusa': preco_minimo_blusa,
		'preco_minimo_calca': preco_minimo_calca,
	}
	return render(req, 'home.html', context)


def category(req, cat):
	products = Produto.objects.filter(categoria=cat).order_by('-id')
	cat_name_full = None

	if cat == "C":
		cat_name_full = 'Casacos'
	elif cat == "M":
		cat_name_full = 'Moletons'
	elif cat == "B":
		cat_name_full = 'Blusas'
	elif cat == "A":
		cat_name_full = 'Calças'

	context = {
		'products': products,
		'cat_name': cat_name_full
	}
	return render(req, 'category.html', context)


def produto(req, slug):
	product = Produto.objects.get(slug=slug)
	context = {'produto': product}

	return render(req, 'product.html', context)


def add_to_cart(req):
	http_referer = req.META.get('HTTP_REFERER')
	variacao_id = req.GET.get('vid')

	# verifying things
	if not variacao_id:
		messages.error(req, 'Selecione o tipo do produto')
		return HttpResponseRedirect(http_referer)

	variacao = get_object_or_404(Variacao, id=variacao_id)
	variation_estoque = variacao.estoque
	produto = variacao.produto

	if variacao.estoque < 1:
		messages.error(req, 'Infelizmente este item está fora de estoque')
		return redirect(http_referer)

	# inicializa sessao do cart se ja nao estiver inicializada
	if not req.session.get('cart'):
		req.session['cart'] = {}
		req.session.save()
	cart = req.session.get('cart')

	# actually adding to cart

	if variacao_id in cart:
		actual_quantity_in_cart = cart[variacao_id]['quantidade']
		actual_quantity_in_cart += 1

		if variation_estoque < actual_quantity_in_cart:
			messages.error(
				req, 
				f'Estoque insuficiente para {actual_quantity_in_cart} {produto.nome}. Apenas {variation_estoque} produtos serão adicionados'
			)
			actual_quantity_in_cart = variation_estoque

		cart[variacao_id]['quantidade'] = actual_quantity_in_cart
		cart[variacao_id]['preco_total'] = variacao.preco * actual_quantity_in_cart
	else:
		cart[variacao_id] = {
			'produto_id': produto.id, 
			'variacao_id': variacao_id,
			'produto_nome': produto.nome, 
			'variacao_nome': variacao.nome, 
			'preco_unitario': variacao.preco,
			'preco_total': variacao.preco,				# total da compra
			'quantidade': 1,
			'slug': produto.slug,
			'imagem': produto.imagem.name,
		}
	
	req.session.save()
	messages.info(req, f'Produto adicionado ao carrinho, {cart[variacao_id]["quantidade"]} total')

	print(cart)
	return HttpResponseRedirect(http_referer)


def cart(req):
	return render(req, 'cart.html')


def remove_from_cart(req, varid):
	http_referer = req.META.get('HTTP_REFERER')

	if not req.session.get('cart'):
		return redirect(http_referer)

	if not varid:
		return redirect(http_referer)

	if varid not in req.session['cart']:
		return redirect(http_referer)
		print('o alguem tentou mecher nos params pra remover do cart')

	product_in_cart = req.session['cart'][varid]
	messages.info(req, f'produto {product_in_cart["produto_nome"]} removido com sucesso')
	# todo: if quantidade > 1 remover 1

	del req.session['cart'][varid]
	req.session.save()
	return HttpResponseRedirect(http_referer)


# @login_required(login_url='login_user')
def summary(req):
	if not req.user:
		messages.error(req, 'você precisa criar uma conta para finalizar um pedido')
		return redirect('create-user')
	
	perfil = req.user.perfil_set.get(user=req.user)
	cart = req.session.get('cart')

	context = {
		'perfil': perfil,
		'user': req.user
	}

	# ------------ checking if the quantity of the product in cart is not > than available
	# and changing it as necesary
	cart_variation_ids = [v for v in cart]
	variations = list(
		Variacao.objects.select_related('produto').filter(id__in=cart)
	)

	for variation in variations:
		v_id = str(variation.id)

		estoque = variation.estoque
		qtd_cart = cart[v_id]['quantidade']

		if estoque < qtd_cart:
			cart[v_id]['quantidade'] = estoque
			cart[v_id]['preco_total'] = estoque * cart[v_id]['preco_unitario']
			req.session.save()

			messages.error(req, 'Estoque insuficiente para alguns produtos do seu carrinho, adicionando a quantidade máxima disponível, por favor revise a compra')

			return redirect('cart')

	return render(req, 'summary.html', context)

produto/templates/cart.html
{% extends 'base.html' %}

{% block content %}
{% include 'partials/_nav.html' %}

<section>

	<h2>Seu carrinho</h2>
	{% if request.session.cart %}

		{{request.session.cart}}
		{% for item in cart.values %}
		{% endfor %}

	{% else %}
		<p>Seu carrinho está vazio, clique <a class="chique a_bold" href="{% url 'home' %}">aqui</a> para voltar à página inicial</p>
	{% endif %}
</section>

{% endblock %}

produto/templates/category.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}
{% include 'partials/_nav.html' %}

<section class="category">
	<h2>Categoria: {{ cat_name }}</h2>

	<div class="product-holder">
		{% for produto in products %}

			<div class="box2">
				<img src="../../media/{{produto.imagem}}" alt="">
				<h3>{{produto.nome}}</h3>
				<p>{{produto.descricao_curta}}</p>
				<a href="{% url 'produto' produto.slug %}" class="box">De
					<span class="price">{{produto.preco_minimo|format_price}}</span> 
					{% if produto.preco_maximo %}
					a
					<span class="price">{{produto.preco_maximo|format_price}}</span>
					{% endif %}
				</a>
			</div>

		{% endfor %}
	</div>
</section>

{% endblock %}

produto/templates/home.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}

<header>
	{% include 'partials/_nav.html' %}
	<section>
		<div>
			<h1>store <br> Loja de Roupas</h1>
			<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolorem deleniti minima cupiditate necessitatibus possimus amet fugit saepe earum excepturi, atque velit dolores optio asperiores odit voluptate alias, repellat ab. Dolorem?</p>
		</div>	

		<aside>
			<!-- <a href="{% url 'category' 'C' %}">
				<div class="box">casacos</div>
			</a>
			<a href="{% url 'category' 'M' %}">
				<div class="box">moletons</div>
			</a>
			<a href="{% url 'category' 'B' %}">
				<div class="box">blusas</div>
			</a>
			<a href="{% url 'category' 'A' %}">
				<div class="box">calças</div>
			</a> -->
		</aside>
	</section>
</header>


<section>
	<h2>Destaques</h2>

	<div class="featured">		
		{% for destaque in destaques %}
	
		<div>
			<a href="{% url 'produto' destaque.slug %}"><img src="../../media/{{destaque.imagem}}" alt=""></a>
			<p>{{destaque.nome}}</p>
			<a href="{% url 'produto' destaque.slug %}"><h3 class="price chique">{{destaque.preco_minimo}}</h3></a>
		</div>
	
		{% endfor %}
	</div>
</section>

<section  class="product-category-chooser">
	
	<div class="item-category">
		<p class="chique">A partir de</p>
		<h3>R${{preco_minimo_casaco}}</h3>
		<a href="{% url 'category' 'C' %}"><img src="https://images.unsplash.com/photo-1582607709337-277eb1e1bad9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" alt="foto de casacos"></a>
		<h2>Casacos</h2>
		<a href="{% url 'category' 'C' %}">Ver Tudo →</a>
	</div>

	<div class="item-category">
		<p class="chique">A partir de</p>
		<h3>R${{preco_minimo_moletom}}</h3>
		<a href="{% url 'category' 'M' %}"><img src="https://images.unsplash.com/photo-1611911813383-67769b37a149?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" alt="photo of a product"></a>
		<h2>Moletons</h2>
		<a href="{% url 'category' 'M' %}">Ver Tudo →</a>
	</div>

	<div class="item-category">
		<p class="chique">A partir de</p>
		<h3>R${{preco_minimo_blusa}}</h3>
		<a href="{% url 'category' 'B' %}"><img src="https://images.unsplash.com/photo-1630004184878-c60794d1c105?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8N3x8YmxvdXNlfGVufDB8MnwwfHw%3D&auto=format&fit=crop&w=400&q=60" alt="photo of a product"></a>
		<h2>Blusas</h2>
		<a href="{% url 'category' 'B' %}">Ver Tudo →</a>
	</div>

	<div class="item-category">
		<p class="chique">A partir de</p>
		<h3>R${{preco_minimo_calca}}</h3>
		<a href="{% url 'category' 'A' %}"><img src="https://images.unsplash.com/photo-1574809736435-dced6ecf6ce7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8OXx8cGFudHN8ZW58MHwyfDB8fA%3D%3D&auto=format&fit=crop&w=400&q=60" alt="photo of a product"></a>
		<h2>Calças</h2>
		<a href="{% url 'category' 'A' %}">Ver Tudo →</a>
	</div>

</section>


{% endblock %}

produto/templates/product.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}
{% include 'partials/_nav.html' %}
<section class="product">

	<img src="../../media/{{produto.imagem}}" alt="">

	<div class="product-details">
		<form action="{% url 'addtocart' %}">
			<div class="one-liner">
				<h2>{{produto.nome}}</h2>
					
				<div>
					{% for variacao in produto.variacao_set.all %}
						<input type="radio" name="vid" value="{{variacao.id}}">
						{{variacao}}
					{% endfor %}
				</div>
							
			</div>
			
			<p>{{produto.descricao_longa}}</p>
			<input class="box submit" type="submit" value="Adicionar ao carrinho">
	
		</form>
	
		<aside class="prices">
			<h3>Preços:</h3>
			{% for variacao in produto.variacao_set.all %}
				<div class="one-liner">
					<p>{{variacao.nome}} - R${{variacao.preco|format_price}}</p>
				</div>
			{% endfor %}
		</aside>
	</div>
</section>
{% endblock %}

produto/templates/summary.html
{% extends 'base.html' %}
{% load static %}
{% load omfilters %}

{% block content %}
{% include 'partials/_nav.html' %}

<section class="cart summary">

	<h2>Resumo da Compra</h2>
	<p>Se precisa editar algo, clique <a class="chique a_bold" href="{% url 'edit-user' %}">aqui</a></p>
	{% if request.session.cart %}

		<!-- {{request.session.cart}} -->

		<h3>Dados Pessoais</h3>
		<div class="info">
			<p>Nome: {{user.first_name}}</p>
			<p>Sobrenome: {{user.last_name}}</p>
			<p>Email: {{user.email}}</p>
			<p>CPF: {{perfil.cpf}}</p>
		</div>

		<h3>Dados de Entrega</h3>
		<div class="info">
			<p>Estado: {{perfil.estado}}</p>
			<p>CEP: {{perfil.cep}}</p>
			<p>Cidade: {{perfil.cidade}}</p>
			<p>Bairro: {{perfil.bairro}}</p>
			<p>Endereço: {{perfil.endereco}}</p>
			<p>Número: {{perfil.numero}}</p>
			<p>Complemento: {{perfil.complemento}}</p>
		</div>
			
		<h3>Itens</h3>

		{% for item in request.session.cart.values %}
			<div class="cart-product-wrapper">
				<img src="../../media/{{item.imagem}}" alt="{{item.produto_nome}}">

				<div>
					<div class="one-liner-dont-break">
						<a class="a_bold" href="{% url 'produto' item.slug %}"><p>{{item.produto_nome}}</p></a> - <p>{{item.variacao_nome}}</p>
					</div>
					<div class="one-liner-dont-break">
						<p>R${{item.preco_unitario|format_price}}</p> x <p>{{item.quantidade}}</p> = 
						<p>R${{item.preco_total|format_price}}</p>
					</div>

				</div>

			</div>
		{% endfor %}

		<h3>total: R${{request.session.cart|cart_total_cost|format_price}}</h3>

		<div class="box2 gotosomewhere">
			<p><a href="{% url 'cart' %}">Voltar</a></p>
		</div>
		<div class="box gotosomewhere">
			<p><a href="{% url 'save' %}">Finalizar</a></p>
		</div>

	{% else %}
		<p>Seu carrinho está vazio, clique <a class="chique a_bold" href="{% url 'home' %}">aqui</a> para voltar à página inicial</p>
	{% endif %}

</section>
{% endblock %}