pedido/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('salvar/', views.save, name='save'),
	path('pagar/<int:pk>', views.pay, name='pay'),
	path('listar/', views.list, name='list'),
	path('detalhesdopedido/<int:pk>', views.order_detail, name='order-detail'),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('produto.urls')),
	path('perfis/', include('perfil.urls')),
	path('pedido/', include('pedido.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pedido/models.py
from django.db import models
from django.contrib.auth.models import User


class Pedido(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	total = models.FloatField()
	qtd_total = models.PositiveIntegerField()
	status = models.CharField(
		default="C",
		max_length=1,
		choices = (
			('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),
		)
	)

	def __str__(self):
		return f'pedido N. {self.pk}'


class ItemPedido(models.Model):
	pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)
	produto_nome = models.CharField(max_length=255)
	produto_id = models.PositiveIntegerField()
	variacao = models.CharField(max_length=255)
	variacao_id = models.PositiveIntegerField()
	preco = models.FloatField()
	quantidade = models.PositiveIntegerField()
	imagem = models.CharField(max_length=2000)

	def __str__(self):
		return f'item {self.produto_nome} do {self.pedido}'

	class Meta:
		verbose_name = 'Item do pedido'
		verbose_name_plural = 'Itens do pedido'

pedido/views.py
from sys import stdout
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .models import ItemPedido, Pedido
from django.contrib.auth.decorators import login_required


@login_required(login_url='login-user')
def save(req):
	cart = req.session.get('cart')

	if not req.user.is_authenticated:
		messages.error(req, 'é preciso ter uma conta para entrar nesta página')
		return redirect('create-user')
	elif not cart:
		messages.error(req, 'carrinho vazio')
		return redirect('home')

	qtd_total_cart = cart_total_qtd(cart)
	total_cart = cart_total_cost(cart)

	pedido = Pedido(
		user = req.user,
		total = total_cart,
		qtd_total = qtd_total_cart,
		status = 'C'
	)
	pedido.save()

	ItemPedido.objects.bulk_create(
		[
			ItemPedido(
				pedido=pedido,
				produto_nome=v['produto_nome'],
				produto_id=v['produto_id'],
				variacao=v['variacao_nome'],
				variacao_id=v['variacao_id'],
				preco=v['preco_unitario'],
				quantidade=v['quantidade'],
				imagem=v['imagem'],
			) for v in cart.values()
		]
	)

	del req.session['cart']

	context = {
		'qtd_total_cart': qtd_total_cart,
		'total_cart': total_cart,
	}
	
	return redirect(reverse('pay', kwargs={'pk': pedido.pk}))


@login_required(login_url='login-user')
def pay(req, pk):
	pedido = Pedido.objects.get(id=pk)

	# redirect to home if user loged is diferent from which the pedido was created
	if pedido.user != req.user:
		return redirect('home')
	
	context = {'pedido': pedido}
	return render(req, 'pay.html', context)


def list(req):
	pedidos = Pedido.objects.filter(user=req.user).order_by('-id')
	context = {'pedidos': pedidos}
	return render(req, 'list.html', context)


def order_detail(req, pk):
	context = {
		'pedido': Pedido.objects.get(id=pk)
	}
	return render(req, 'order-detail.html', context)

# --------------------------------- helpers ------------------------------------
def cart_total_qtd(carrinho):
    return sum([item['quantidade'] for item in carrinho.values()])


def cart_total_cost(cart):
	return sum(
		[
			item.get('preco_total')
			for item 
			in cart.values()
		]
	)

pedido/templates/list.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}
{% include 'partials/_nav.html' %}
<section>

  <h2>Seus Pedidos</h2>

  <div class='orders'>
	{% for pedido in pedidos %}

	{% if pedido.status == 'F' %}
	<div class='order box2'>
	{% else %}
	<div class='order box'>  
	{% endif %}
	  <h3> {{pedido}}</h3>
	  <p>Total: R${{pedido.total|format_price}}</p>
	  <p>Quantidade de Itens: {{pedido.qtd_total}}</p>
	  <p>Status: {{pedido.get_status_display}}</p>
	  <a class='a_bold' href="{% url 'order-detail' pedido.id %}">Detalhes</a>
	</div>
	
	{% endfor %}
  </div>
	
</section>
{% endblock %}

pedido/templates/order-detail.html
{% extends 'base.html' %}
{% load omfilters %}
{% load mathfilters %}

{% block content %}
{% include 'partials/_nav.html' %}
<section>

  <h2>{{pedido}} </h2>

  <h3>Itens</h3>

  {% for item in pedido.itempedido_set.all %}
  <div class="cart-product-wrapper">
	<img src="../../media/{{item.imagem}}" alt="{{item.produto_nome}}">

	<div>
	  <div class="one-liner-dont-break">
		<p>{{item.produto_nome}}</p> - <p>{{item.variacao}}</p>
	  </div>
	  <div class="one-liner-dont-break">
		<p>R${{item.preco|format_price}}</p> x <p>{{item.quantidade}}</p> = 
		<p> R${{ item.preco|mul:item.quantidade}}</p>
	  </div>

	</div>

  </div>
  {% endfor %}

  <h3>total: R$ {{pedido.total}}</h3>
	
</section>
{% endblock %}

pedido/templates/pay.html
{% extends 'base.html' %}
{% load omfilters %}

{% block content %}
{% include 'partials/_nav.html' %}
<section>

  <h2>Escolha o método de pagamento</h2>

  <p>
		Pedido N. {{pedido.id}} <br/>
		QTD. Items {{pedido.qtd_total}} <br/>
		Total R${{pedido.total|format_price}} <br/>
		Status {{pedido.get_status_display}}
  </p>
  
	<!-- {% for item in pedido.itempedido_set.all %}
	<div class="cart-product-wrapper">
		<img src="../../media/{{item.imagem}}" alt="{{item.produto_nome}}">

		<div>

			<div class="one-liner-dont-break">
				<p>{{item.produto_nome}}</p> - <p>{{item.variacao}}</p>
			</div>
			<div class="one-liner-dont-break">
				<p>R${{item.preco|format_price}}</p> x <p>{{item.quantidade}}</p>
			</div>

		</div>

	</div>
	{% endfor %} -->
	
	<div class="box gotosomewhere">
		<p><a href="">PagSeguro</a></p>
	</div>

</section>
{% endblock %}